apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvlink
  namespace: argocd
spec:
  project: nvlink
  source:
    repoURL: https://github.com/gateszhangc/nvlink.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: nvlink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

