apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvlink

resources:
  - ../../base
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: true

images:
  - name: nvlink
    newName: registry.144.91.77.245.sslip.io/nvlink
    newTag: 49e877f1ab9799a5f13def97492cfda4a55474a6

